apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: my-container
        image: alpine:latest
        command: ["sleep", "infinity"]
